const { captionPresetAction } = require('./caption-ui-helpers.cjs')
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { buildApp, launchApp } = require('../zernio/support/electron-app.cjs')
const { loadMain } = require('../zernio/support/load-main.cjs')
const { defaultCaptionStyle } = loadMain("export { defaultCaptionStyle } from './src/shared/custom-captions'")

test('browse defaults beside custom presets and keep bookmarks through selection, editing, deletion and restart', { timeout: 120000 }, async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bridgeclip-caption-favorites-'))
  const appDir = buildApp(path.join(root, 'app')), userDataDir = path.join(root, 'data')
  let session = await launchApp({ appDir, userDataDir })
  t.after(async () => { await session.close(); fs.rmSync(root, { recursive: true, force: true }) })
  const { app, page } = session
  page.setDefaultTimeout(10000)
  await app.evaluate(({ BrowserWindow, ipcMain }, root) => {
    BrowserWindow.getAllWindows()[0].setSize(1200, 1000)
    BrowserWindow.getAllWindows()[0].webContents.setBackgroundThrottling(false)
    for (const [channel, handler] of [
      ['settings:load', () => ({ openrouterConfigured: true, zernioConfigured: false, outputDirectory: root, pythonPath: '' })],
      ['system:checkTools', () => ({ python: true, pythonDeps: true, ffmpeg: true, ffmpegCaptions: true, ffprobe: true, ytdlp: true, engine: true, bridgeRunner: true })]
    ]) { ipcMain.removeHandler(channel); ipcMain.handle(channel, handler) }
  }, root)
  const preset = { id: 'custom-studio', name: 'Studio Mint', baseId: 'pop', style: defaultCaptionStyle('pop') }
  await page.evaluate(preset => window.bridgeclip.captions.save(preset), preset)
  await page.reload()
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.evaluate(() => {
    Object.defineProperty(document, 'hidden', { configurable: true, get: () => false })
    Object.defineProperty(document, 'visibilityState', { configurable: true, get: () => 'visible' })
  })
  const nav = name => page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name, exact: true })
  const shot = async name => {
    if (!process.env.BRIDGECLIP_E2E_SHOTS) return
    fs.mkdirSync(process.env.BRIDGECLIP_E2E_SHOTS, { recursive: true })
    // Capture a spoken frame, rather than the recording's opening silence.
    const seek = page.getByRole('slider', { name: 'Caption preview position', exact: true })
    await seek.evaluate(input => {
      Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(input, '230')
      input.dispatchEvent(new Event('input', { bubbles: true }))
      input.dispatchEvent(new Event('change', { bubbles: true }))
    })
    await page.waitForFunction(() => Math.abs(document.querySelector('[aria-label="Caption preview"] audio').currentTime - .23) < .025)
    await page.evaluate(() => document.fonts.ready)
    await page.screenshot({ path: path.join(process.env.BRIDGECLIP_E2E_SHOTS, name), animations: 'disabled' })
  }
  await nav('Captions').click()
  const presets = page.getByRole('radiogroup', { name: 'Your caption presets' })
  const defaults = page.getByRole('radiogroup', { name: 'Default caption presets', exact: true })
  await presets.waitFor()
  assert.equal(await defaults.getByRole('radio').count(), 13)
  const preview = page.getByRole('region', { name: 'Caption preview', exact: true })
  const assertStill = async () => {
    await preview.getByRole('button', { name: 'Play caption preview', exact: true }).waitFor()
    await page.waitForFunction(() => document.querySelector('[aria-label="Caption preview"] audio')?.readyState >= 2)
    assert.equal(await preview.locator('audio').evaluate(el => el.paused && el.currentTime === 0), true)
    assert.equal(await preview.locator('[data-caption-state="active"]').evaluate(el => getComputedStyle(el).visibility), 'visible', 'the paused opening frame contains visible captions')
  }
  for (const name of ['Pop', 'Spotlight', 'Impact', 'Glow', 'Boxed', 'Sweep', 'Editorial', 'Hype', 'Punch', 'Neon', 'Headline', 'Paper', 'Subtle']) {
    await defaults.getByRole('radio', { name, exact: true }).click()
    await assertStill()
  }
  await preview.getByRole('button', { name: 'Enable preview audio', exact: true }).click()
  await assertStill()
  await preview.getByRole('button', { name: 'Play caption preview', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('[aria-label="Caption preview"] audio')?.currentTime > .15)
  const oldAudio = await preview.locator('audio').elementHandle()
  await defaults.getByRole('radio', { name: 'Pop', exact: true }).click()
  assert.equal(await oldAudio.evaluate(el => el.paused), true)
  await oldAudio.dispose()
  await assertStill()
  assert.equal(await preview.locator('audio').evaluate(el => el.muted), false, 'sound preference is preserved without autoplay')
  await nav('Jobs').click()
  await nav('Captions').click()
  await assertStill()
  await page.waitForTimeout(200)
  await assertStill()
  if (process.env.BRIDGECLIP_E2E_SHOTS) {
    fs.mkdirSync(process.env.BRIDGECLIP_E2E_SHOTS, { recursive: true })
    await page.screenshot({ path: path.join(process.env.BRIDGECLIP_E2E_SHOTS, 'captions-paused.png') })
  }
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await defaults.getByRole('button', { name: 'Bookmark Paper', exact: true }).click()
  assert.equal(await defaults.getByRole('radio', { name: 'Pop', exact: true }).getAttribute('aria-checked'), 'true', 'bookmarking does not select a different style')
  await presets.getByRole('button', { name: 'Bookmark Studio Mint', exact: true }).click()
  assert.equal(await page.getByRole('textbox', { name: 'Style name', exact: true }).count(), 0, 'bookmarking does not open an edit')
  await shot('captions-defaults-favorites.png')

  await nav('Create').click()
  await page.getByPlaceholder('YouTube, Twitch VOD or direct video link').fill('https://example.com/captions.mp4')
  await page.getByRole('button', { name: 'Use link', exact: true }).click()
  await page.getByRole('radio', { name: 'Automatic', exact: true }).click()
  await page.getByRole('navigation', { name: 'Create steps' }).getByRole('button', { name: /Captions/ }).click()
  const allDefaults = page.getByRole('radiogroup', { name: 'Caption style', exact: true })
  const custom = page.getByRole('radiogroup', { name: 'Your caption styles', exact: true })
  const filters = page.getByRole('radiogroup', { name: 'Caption style filter', exact: true })
  assert.equal(await allDefaults.getByRole('radio').first().getAttribute('aria-label'), 'Paper', 'bookmarks come first')
  assert.equal(await custom.getByRole('radio', { name: 'Studio Mint', exact: true }).getAttribute('aria-checked'), 'true', 'custom bookmarks take priority over built-in bookmarks')
  assert.equal(await allDefaults.getByRole('radio', { name: 'Paper', exact: true }).getAttribute('aria-checked'), 'false')
  await filters.getByRole('radio', { name: /Favorites/ }).click()
  assert.equal(await allDefaults.getByRole('radio').count(), 1)
  assert.equal(await custom.getByRole('radio').count(), 1)
  await page.getByText('Studio Mint preview', { exact: true }).waitFor()
  await custom.getByRole('radio', { name: 'Studio Mint', exact: true }).click()
  await shot('captions-wizard-favorites.png')
  await allDefaults.getByRole('button', { name: 'Remove bookmark from Paper', exact: true }).click()
  await allDefaults.waitFor({ state: 'detached' })
  assert.equal(await custom.getByRole('radio', { name: 'Studio Mint', exact: true }).getAttribute('aria-checked'), 'true')
  await page.waitForFunction(() => document.activeElement?.closest('[aria-label="Caption style filter"]'))
  await custom.getByRole('button', { name: 'Remove bookmark from Studio Mint', exact: true }).click()
  await page.getByText('Bookmark a style to find it here.', { exact: false }).waitFor()
  await page.getByText('Studio Mint preview', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'Browse all styles', exact: true }).click()
  await custom.getByRole('button', { name: 'Bookmark Studio Mint', exact: true }).click()
  await allDefaults.getByRole('radio', { name: 'Pop', exact: true }).focus()
  await page.keyboard.press('ArrowRight')
  assert.equal(await allDefaults.getByRole('radio', { name: 'Spotlight', exact: true }).getAttribute('aria-checked'), 'true', 'arrow keys cross tile wrappers, not bookmark controls')
  await custom.getByRole('radio', { name: 'Studio Mint', exact: true }).click()

  await page.getByRole('button', { name: 'Open captions lab', exact: true }).click()
  await defaults.getByRole('radio', { name: 'Paper', exact: true }).click()
  await presets.waitFor()
  await page.getByRole('button', { name: 'Use preset', exact: true }).click()
  assert.equal(await allDefaults.getByRole('radio', { name: 'Paper', exact: true }).getAttribute('aria-checked'), 'true', 'using a default clears the custom snapshot')
  assert.equal(await custom.getByRole('radio', { name: 'Studio Mint', exact: true }).getAttribute('aria-checked'), 'false')
  await allDefaults.getByRole('button', { name: 'Bookmark Paper', exact: true }).click()
  await page.getByRole('button', { name: 'Open captions lab', exact: true }).click()
  await captionPresetAction(page, 'Studio Mint', 'Edit preset')
  await assertStill()
  await page.getByRole('textbox', { name: 'Style name', exact: true }).fill('Studio Rose')
  await page.getByRole('button', { name: 'Save preset', exact: true }).click()
  await page.getByText('All changes saved', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'Back to presets', exact: true }).click()
  await presets.getByRole('button', { name: 'Remove bookmark from Studio Rose', exact: true }).waitFor()
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(720, 800))
  await page.waitForFunction(() => window.innerWidth === 720 && document.documentElement.scrollWidth <= window.innerWidth)
  await shot('captions-defaults-compact.png')
  await captionPresetAction(page, 'Studio Rose', 'Delete')
  await page.getByRole('dialog', { name: 'Delete preset?' }).getByRole('button', { name: 'Delete preset', exact: true }).click()
  await page.getByRole('heading', { name: 'Choose a base', exact: true }).waitFor()
  assert.deepEqual(await page.evaluate(() => JSON.parse(localStorage.getItem('bridgeclip.captions.favorites'))), ['paper'])

  await session.close()
  session = await launchApp({ appDir, userDataDir })
  await session.page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: 'Captions', exact: true }).click()
  await session.page.getByRole('button', { name: 'Remove bookmark from Paper', exact: true }).waitFor()
  assert.deepEqual(await session.page.evaluate(() => JSON.parse(localStorage.getItem('bridgeclip.captions.favorites'))), ['paper'])
})
