const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { buildApp, launchApp } = require('../zernio/support/electron-app.cjs')

test('reselecting sidebar roots preserves mounted content, scroll and filters; details still navigate with save guards', { timeout: 90000 }, async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bridgeclip-sidebar-'))
  const userDataDir = path.join(root, 'data')
  for (let index = 1; index <= 24; index++) {
    const run = path.join(userDataDir, 'BridgeClip', `run-${index}`)
    fs.mkdirSync(run, { recursive: true })
    fs.writeFileSync(path.join(run, 'job_output.json'), JSON.stringify({ job_id: `run-${index}`, source_video_title: `Navigation run ${index}`,
      source_video_url: 'source.mp4', source_video_duration_seconds: 30, total_clips: 0, clips: [], created_at: '2026-09-29T12:00:00Z' }))
  }
  const session = await launchApp({ appDir: buildApp(path.join(root, 'app')), userDataDir })
  t.after(async () => { await session.close(); fs.rmSync(root, { recursive: true, force: true }) })
  const { app, page } = session
  page.setDefaultTimeout(10000)
  const errors = []; page.on('pageerror', error => errors.push(error.message))
  await app.evaluate(({ BrowserWindow }) => {
    BrowserWindow.getAllWindows()[0].setSize(1200, 700)
    BrowserWindow.getAllWindows()[0].webContents.setBackgroundThrottling(false)
  })
  const nav = name => page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name, exact: true })
  const settle = () => page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
  const shortcut = key => `${process.platform === 'darwin' ? 'Meta' : 'Control'}+${key}`
  const roots = [['Create', '1'], ['Library', '2'], ['Jobs', '3'], ['Captions', '8'], ['Chat', '7'], ['Accounts', '4'], ['Posts', '5'], ['Automations', '6'], ['Settings', ',']]
  for (const [name, key] of roots) {
    await nav(name).click()
    await page.locator('#page-scroll > *').first().waitFor()
    await settle()
    const content = await page.locator('#page-scroll > *').first().elementHandle()
    await nav(name).click()
    await nav(name).click()
    await page.keyboard.press(shortcut(key))
    await settle()
    assert.equal(await content.evaluate(el => el.isConnected && el === document.querySelector('#page-scroll > *')), true, `${name} keeps the same content after repeated clicks and its keyboard shortcut`)
    await content.dispose()
  }
  await nav('Library').click()
  await page.getByRole('button', { name: 'Open Navigation run 1', exact: true }).waitFor()
  const search = page.getByRole('textbox', { name: 'Search runs', exact: true })
  await search.fill('Navigation')
  const scroll = page.locator('#page-scroll')
  await scroll.evaluate(el => { el.scrollTop = 180 })
  const before = await scroll.evaluate(el => el.scrollTop)
  assert.ok(before > 0)
  await nav('Library').click()
  await settle()
  assert.equal(await search.inputValue(), 'Navigation')
  assert.equal(await scroll.evaluate(el => el.scrollTop), before, 'sidebar reselect preserves scroll')
  await search.focus()
  await page.keyboard.press(shortcut('2'))
  await settle()
  assert.equal(await search.evaluate(el => el === document.activeElement), true, 'the current-page shortcut preserves input focus')
  assert.equal(await search.inputValue(), 'Navigation')
  // Library details still return to the root; a subsequent click is a no-op.
  await page.getByRole('button', { name: 'Open Navigation run 1', exact: true }).click()
  await page.getByRole('heading', { name: 'Navigation run 1', exact: true }).waitFor()
  await nav('Library').click()
  await page.getByRole('heading', { name: 'Library', exact: true }).waitFor()
  const library = await page.locator('#page-scroll > *').first().elementHandle()
  await nav('Library').click()
  await settle()
  assert.equal(await library.evaluate(el => el.isConnected), true, 'returning from details restores the root guard')
  // Reselecting Captions while editing is real navigation and still protects the draft.
  await nav('Captions').click()
  await page.getByRole('button', { name: 'Customize', exact: true }).click()
  const name = page.getByRole('textbox', { name: 'Style name', exact: true })
  await name.fill('Keep this draft')
  await nav('Captions').click()
  const prompt = page.getByRole('dialog', { name: 'Save changes before leaving?' })
  await prompt.getByRole('button', { name: 'Keep editing', exact: true }).click()
  assert.equal(await name.inputValue(), 'Keep this draft')
  await page.keyboard.press(shortcut('8'))
  await prompt.getByRole('button', { name: 'Discard', exact: true }).click()
  await name.waitFor({ state: 'detached' })
  await page.getByRole('button', { name: 'Customize', exact: true }).waitFor()
  assert.deepEqual(errors, [])
})
