const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { buildApp, launchApp } = require('../zernio/support/electron-app.cjs')
const { storageRun } = require('../support/storage-fixtures.cjs')

test('Settings previews published cleanup and finished source files before deleting only selected local content', { timeout: 90000 }, async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bridgeclip-storage-ui-'))
  const userDataDir = path.join(root, 'user-data'), library = path.join(userDataDir, 'BridgeClip')
  const automatic = storageRun(library, 'Published interview', { posted: [0, 1] })
  const session = await launchApp({ appDir: buildApp(path.join(root, 'app')), userDataDir })
  t.after(async () => { await session.close(); fs.rmSync(root, { recursive: true, force: true }) })
  const { app, page } = session
  page.setDefaultTimeout(10000)
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1200, 1000))
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  const storage = page.getByRole('region', { name: 'Content storage', exact: true })
  const sources = page.getByRole('region', { name: 'Source file storage', exact: true })
  const publishButton = storage.getByRole('button', { name: 'Clean published content', exact: true })
  await publishButton.waitFor()
  await page.waitForFunction(() => !document.querySelector('[aria-label="Refresh storage usage"]').disabled)
  assert.equal(await sources.count(), 0, 'Automatic-only users do not see editor source controls')
  const mixed = storageRun(library, 'Conversation highlights', { posted: [0], editor: true, sourceBytes: 4_000_000, previewBytes: 1_000_000 })
  const ready = storageRun(library, 'Finished workshop', { editor: true, sourceBytes: 6_000_000, previewBytes: 2_000_000 })
  const editing = storageRun(library, 'Still refining', { editor: true, unfinished: true, sourceBytes: 3_000_000, previewBytes: 500_000 })
  await storage.getByRole('button', { name: 'Refresh storage usage' }).click()
  await sources.getByText('Source videos', { exact: true }).locator('..').getByText('13 MB', { exact: true }).waitFor()
  await sources.getByText('3.5 MB', { exact: true }).waitFor()
  await sources.getByText('Ready to free · 2 projects', { exact: true }).waitFor()
  const shots = process.env.BRIDGECLIP_E2E_SHOTS
  if (shots) { fs.mkdirSync(shots, { recursive: true }); await storage.screenshot({ path: path.join(shots, 'content-storage.png') }) }

  await publishButton.click()
  const published = page.getByRole('alertdialog', { name: 'Clean published content?', exact: true })
  await published.getByRole('status', { name: 'Cleanup space estimate' }).waitFor().catch(async error => { t.diagnostic(await published.innerText()); throw error })
  await published.getByRole('checkbox', { name: 'Published interview', exact: true }).waitFor()
  assert.equal(await published.getByRole('button', { name: 'Cancel', exact: true }).evaluate(el => el === document.activeElement), true)
  assert.equal(await published.getByRole('checkbox').count(), 2)
  const estimate = published.getByRole('status', { name: 'Cleanup space estimate' })
  const before = await estimate.innerText()
  await published.getByRole('checkbox', { name: 'Published interview', exact: true }).uncheck()
  assert.notEqual(await estimate.innerText(), before, 'selection updates the free-space estimate')
  await published.getByRole('button', { name: 'Deselect all', exact: true }).count().then(async count => {
    if (count) await published.getByRole('button', { name: 'Deselect all', exact: true }).click()
  })
  await page.keyboard.press('Escape')
  assert.equal(await published.count(), 0)
  assert.equal(fs.existsSync(automatic.run), true)
  assert.equal(fs.existsSync(mixed.clips[0].s3_url), true)
  await publishButton.click()
  await published.getByRole('checkbox', { name: 'Published interview', exact: true }).waitFor()
  if (shots) await published.screenshot({ path: path.join(shots, 'published-cleanup.png') })
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(720, 760))
  await page.waitForFunction(() => window.innerWidth === 720 && document.documentElement.scrollWidth <= window.innerWidth)
  assert.equal(await published.evaluate(el => el.scrollWidth <= el.clientWidth), true)
  if (shots) await page.screenshot({ path: path.join(shots, 'published-cleanup-compact.png') })
  // A status changed after review: the backend keeps this project, while
  // cleaning the unaffected project selected in the same confirmation.
  fs.unlinkSync(path.join(mixed.run, '.bridgeclip-posted-0'))
  await published.getByRole('button', { name: 'Delete local files', exact: true }).click()
  await storage.getByText(/Cleaned 1 project\. 1 changed since the preview/).waitFor()
  assert.equal(fs.existsSync(automatic.run), false)
  assert.equal(fs.existsSync(mixed.clips[0].s3_url), true)

  await sources.getByRole('button', { name: 'Review sources', exact: true }).click()
  const sourceDialog = page.getByRole('alertdialog', { name: 'Free source media?', exact: true })
  await sourceDialog.getByRole('checkbox', { name: 'Still refining', exact: true }).waitFor()
  assert.equal(await sourceDialog.getByRole('checkbox', { name: 'Still refining', exact: true }).isDisabled(), true)
  await sourceDialog.getByRole('checkbox', { name: 'Conversation highlights', exact: true }).uncheck()
  await sourceDialog.getByText('8 MB', { exact: true }).first().waitFor()
  if (shots) await sourceDialog.screenshot({ path: path.join(shots, 'source-cleanup.png') })
  await sourceDialog.getByRole('button', { name: 'Free source media', exact: true }).click()
  await sourceDialog.waitFor({ state: 'detached' })
  await sources.getByText('7 MB', { exact: true }).waitFor()
  assert.equal(fs.existsSync(path.join(ready.run, 'editor-source.mp4')), false)
  assert.equal(fs.existsSync(path.join(ready.run, 'editor-preview.mp4')), false)
  assert.equal(fs.existsSync(ready.clips[0].s3_url), true)
  assert.equal(JSON.parse(fs.readFileSync(path.join(ready.run, 'editor-project.json'))).media_freed, true)
  assert.equal(fs.existsSync(path.join(mixed.run, 'editor-source.mp4')), true)
  assert.equal(fs.existsSync(path.join(editing.run, 'editor-source.mp4')), true)
  await publishButton.click()
  await published.getByText('No published content ready to clean.').waitFor()
  assert.equal(await published.getByRole('button', { name: 'Delete local files' }).count(), 0)
  await published.getByRole('button', { name: 'Done' }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await sources.getByText('Ready to free · 1 project', { exact: true }).waitFor()
  await app.evaluate(({ ipcMain }) => {
    ipcMain.removeHandler('settings:previewCleanup')
    ipcMain.handle('settings:previewCleanup', () => { throw new Error('Library unavailable. Try refreshing.') })
  })
  await publishButton.click()
  await published.getByRole('alert').getByText(/Library unavailable/).waitFor()
  assert.equal(await published.getByRole('button', { name: 'Delete local files', exact: true }).isDisabled(), true)
  await published.getByRole('button', { name: 'Cancel', exact: true }).click()
  assert.deepEqual(errors, [])
})
